server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      #设置与Eureka Server 地址
      defaultZone: http://localhost:8083/eureka/


